from random import randint
"""
Topics we can talk about: 
1. Hype & Words and safety
2. Helping new memebers 
3. Magic Eden, Rug and All the rest
"""
#Important links
check_invites = ""
get_whitelist = "#❓┃faq  "

#This should only be used in the discord server: "The Metanoids"
helping_members = ["Ask me any questions, I'd be glad to help", "I've no intention to spam the channel. Just helping new members. To know\
how you can get whitelisted, use this channel link: {}".format(get_whitelist), "If you want to get whitelisted, follow the instructions in:{}".format(get_whitelist), "New members can find out whitelist info here: {}".format(get_whitelist),
"Keep grinding and vibing, you'll get whitelist. Also don't forget to check this channel for more information:{}".format(get_whitelist), "New members could find out about whitelist info using this channel:{}".format(get_whitelist), 

]

word = ['magic eden is a crappy website', 'Lmao I think they know what they\'re doing.', "Who was on the balloonville rug? It was so pathetic", 
"who have seen this project's roadpaper", "I like the arts to be honest!", "This is the best project", "This project is better than the ones I minted before", 
"I didn't know about NFTs until my cousin brother introduced me to it.", "I like that the mods of this project are very active","Wisdom is easily acquired when you mint the wrong project multiple times. Lmao", 
"Going from child, to childish, to childlike is only a matter of time.", "I checked to make sure that he was still alive", "Could someone help me tell the newbies that are here never to share\
never to share their paraphrase with anybody?" "Nobody questions who is the founder of Magic Eden.", "Why is there too many fud in this project?", "I just don't want it to be what I'm thinking.",
"How can get whitelist?", "What's the best way to get whitelist?" ,"I'm fine and you?", "Let those who have whitelist speak.", "Let's help everyone in the community. ", 
"A good project is determined by the community", "We don't really care much about the art. \nIt's the community that counts. Lol", "What's the supply for this project?", 
"Apart from project, what next do you look out for in a project?", "Making sure this is the right thing to do. LOl", "I was clicking the mint button. It didn't work until I saw sold out!! I was so pained.", 
"Some days, I wish I could just get whitelisted simply by inviting memebers to the group and not by chatting.", "Y'all can't believe I'm chatting from the lecture hall.", 
"Why does my phone beep anytime someone sends a message?", "If opensea could integrate phantom wallet to their website eventually.", "If you're new to the group, ask me anything, I will answer you. \nThis is the best project ever. Lmao", 
"Who is in the mile high ape club?", "Fellowship Dao didn't moon as high as I anticipated", "Balloonville was initially a rug, perhaps the devs changed their mind", "I like that this group doesn't have slow mode.", 
"Am I supposed to submit my wallet address here after the whitliest?", "How do I know it's my time in UTC?", "How do I convert UTC time to my time?", "How lucrative do you think NFTs are?", 
"Lol. This community is very busy.", "How can you tell if this is a good project? ", "My favorite mint so far was botborgs.", "What's most painful is getting whitelisted but forgetting\
to submit your address","Would you advise anyone to drop out of school just to trade NFTs?", "Stop asking how to get whitelisted. Just vibe in the group and trust me, the devs will get you whitelisted.", 
"Some people are just here for the whitelist and that's not the best thing to do.", "Make sure you turn off your direct messages to avoid scammers.", "Am I the only one who uses phantom, why nobody uses sollet?", 
"Ethereum NFTs are very lucrative but the gas fees are so high", "My mom didn't know I've made twice my school fees trading NFTs.", "My Dad is so busy that I only see him once in a week.  Only on sundays. Lol", 
"How do you ensure that you're not making mistake?", "Hey, How are you doing?", "Welcome to the community.", "How are you?", "Lol. Been here for more than 3 days.", "Just keep vibing, The Devs are watching.", 
"This whitelisting model will be hard for influencers to take advantage of.", "I know what they're doing", "They also have instagram", "Telegram is full of scammers. Lol", "I'm just looking out for one thing.", 
"Just making sure that it's not as annoying as I think it is.", "The recent pump in crypto could be a bull trap.", "Now that the price of solana is cheap, you'd gain more by buying. Even if you buy the wrong NFT, you'd benefit when it pumps", 
"I'm just chilling", "What is that?", "Maybe", "Hlo", "Yeah", "Okay", "Not really", "Lol", "I don't understand.", "I mistakenly downloaded a program that changes a wallet address when you copy it from metamask.", 
"Whatever.", "How busy is this place?", "Wyd", "Nothing", "I'm Nigerian", "What about you?", "How was your day?", "What's the time in your place?", "I see this is the best project", "Making sure this isn't a rug.", 
"I only come here when I'm free.", "Just know that the paperhands are here. Lol", "The same people who are hyping it will still list below mint price.", "Most influencers are the ones that dump most projects", 
"influencers are usually the first people to dump the project", "NFT isn't like crypto", "Have you followed their twitter handle?", "I know what to do.", "We're vibing Bro. We ain't grinding", "Make sure you're catching vibes on vibes.", 
"This projec is very nice.", "Imagine what would've happened if you were there", "Chilling", "Just chatting", "Lol Are you blushing?", "Make sure you submit your wallet address after the whitelist.", 
"Hey fam", "Are you just joing the channel?", "Have you verified your account?", "Turn off your dm", "Alright", "Hmmmm", "I don't know", "Ohh", "Really?", "Maybe", "Lmao", "Idk", "That's why I'm so humble. Lol",
"influencers are usually the first people to dump the project", "More and more", "I think there is a section for WL to send their address", "thanks mads", "Let's claim it bro","how long have you been here?","Hey everyone"
"I’m good. How was ur day,""doing well! blessed! how you doing?","yo how is everyone doing","Guys if u have some questions, feel free to ask😅 we help you! 😄",'vibing here while at wok. hbu?',"Keep grinding guys",
"Congrats to the WL winners 💯💯","know where to check level dash?","love this project and im trying to help build community","We're almost bro. Just keep on grinding 🤝","I wonder when they will announcement about the giveaways.",
"yeah of course.  we have a genuine conversation here and not for leveling up.  Im here cause i want to talk someone who are from different Country 🙂 ",
"do u really need high lvl to get WL or just be cool in the chat cuz i find it quitedifficult to stay up here all day","exactly dont give up, we have the best community💪🏼💪🏼💪🏼","todays the big day!","Is there a WL token?",
"how many people are whitelisted","Where is minting taking place?","is WL closed?","this channel is wonderful, there are very nice participants and moderators here, here I really rest my soul🥰","some people have to work hard and some people have to have lucky 😂",
"Dope community right","Let's bring out the good vibes","Everyone keep on spreading positive  vibes they’re not looking for high ranks  but for genuine people who want to be apart of the community! Let them know we are team players.",
"hello people","Great project to be involved in, what are your thoughts","Yea but right now most of my time is occupied with school and NFTs. I don't really have the urge to play anymore. It's good though I spend it more productively.",
"Anayone from french?","Goodmorning homies how’s the day looking","I understand you, it's always a shame when your efforts don't lead to anything, but if you're wrong, then you're on the right track, don't give up ❤️",
"Feel free to ask question in here.","Make them want to wl you, be here for the community! Show a passion for the project! Show them your a diamond hand!!!!!!’","Less go boys keep the chat hyped","Gm bro how’s your day been!?","Morning fam. How you all doing today",
"I’m trying to work and be here, very productive 😅","New members Do not fall for any dms asking you to mint...or Fill a form asking for passphrase...be very watchful","bro im here for so long i dont\
 even know what can i write","With money come's great responsibility make sure you are in charge of your money make sure you choose the right projects make sure that everyone you know is well off you will achieve financial freedom\
 Once I get WLed, I'll press on and keep chatting like I never got WLed","This is an amazing community with great people in great leaders","Less goo wL","Hope you all make to the WL ! goodluck to everyone and cheers .Stay vibin and spread that positve energy",
"Just infuse good vibes and positive energy here and you'd be blessed","Keep it real guys" ,"And you'll get whatever you're looking for","hi cutieeee how do u feel??","You minting any other nfts","That’s great and same I also met so many nice people here",
"Amazing community","Yeah it looked nice btw glad to see your still here","Yeah it looked nice btw glad to see your still here","You got this fam","Welcome all new members guys if u have some questions, feel free to ask😅 we help you! 😄","heyyyyy how are you buddie ??",
"Lets work, no pain no gain","Cool bro. keep at it", "If you have lot of liesure time", "I will be glad if I saw your name in black today", "Oh that’s not up yet. Cool. Imma buy my two and then wait for the update", "Does it even matter? Lmao", "You can tell by the way he was creating FUD", 
"Hey... You just joined the group 5 minutes ago. Now you said this is a good project", "I hear he goes and flips degen coin", "not for me", "Don’t do it he just goes and gambles on degen flip. He just posted in another discord not 15 mins ago", "Guys, I'm new to this. I know some here lost to scam and also just want to know what projects from your perspective are good for you. If you share it, I would really appreciate it.", 
"i just want people not to paperhand....cause good project", "Always buy on magiceden. Never never buy through dms. Thats how u get scammed.", "I hate spending so much time grinding for whitelist only to discover that the whitelist token can be bought", "I am really excited for the staking announcement on Sunday, I have five dragons lol lol, I think moon, the community is also awesome", "same, i bought two rares and one epic at around 2-3 sol yesterday",
"Fake fomo hype It'll come back down lol the fp if we just sweep. We need big announcements", "agree in a way, but what other options do we have ..", "let's hope this goes to the moon", "i think so, it so late in indo", "That's unfortunate. Were u injured?", "Y make me more envious hahaha", "Sowwy", "My friend broke his jaw", "it depends on location and what food u want to order", "And look when I called it", "Yeah i know about that project. Some kind of investment Company launch their nft", 
"Glad I sniped my mythic at 8.5 cuz we taking off 🚀", "I’m using a Mac when I login to solaland and click sign it just disappears and It doesn’t show that I’m verified even though I’m clicking over and over, I know the dev can hook me up if he gets the chance", "Yeah... I have no idea why they banned my first discord.", "aped in, everything looks fire in here", "Joining this community one of my best decisions.", 
"Idk. I've been doing NFTs for a year and half and I can confidently tell you that most projects with too much hype don't do well.", "I see good potential in this projects.", "It's even the whitelisted people that will first paperhand the project", 
"There is no time", "Keep the energy guys", "Once I do my due diligence about a project, I don't really give much ear to FUD", "Thank God say our L no too much", "E been get hype but e no come do well", "life’s tough. recognize the ones who really care about you and hold on tight to them.", 
"And please if you're just joing this server, don't mind to ask me any question. I'm not one of the admins but I'm here to help", "Lots of people buying comic book NFTs. How many of y'all have actually read a comic book? Face with tears of joy", "People think I’m gatekeeping Face with tears of joyFace with tears of joy Never read a comic in my life, relax", 
"Who cares…new times!", "The Devs are very active. You can ask them anything.", "Great vibes in here 🤝🤝🥰", "I'm Nigerian. Lol","I have deleted 4 phishing websites today.. Y’all be careful out there. Street is cold 🥶", "haters hate while we elevate\
Wagmi team", "I’m so bullish about this project. We freaking going to the moon rocket 🚀", "if phishing heats up don't worry, that means you are getting better!!\
Wagmi frens", "Please listen guys :)! Stay safe ❤️", "Why is it getting hot in these NFT street’s lately", "I'm actually starting a 100sol challenge next week. I hope this project doesn't flop.", "Hello MOD let me know if u need me to kick anybodys ass i got ya back 😀", 
"Never a dull day 🙂", "Most recent “NFT influencers” got lucky on one trade and are now fronting as good traders, but make most of their money through whitelists given to them to promote projects.", "It’s okay. I’d be your girlfriend 👀", "Might as well gring and vibe ",
"I hope we get to see more transparency about the founders of this project.", "We truly want a fair system on the mint day sir 🙏🏼", "Hoping for really pleasant, beautiful and successful mint", "😂 you guys got a good sense of humor. I’ll stick around", "They really care about the community.  🤝", 
"People don't acknowledge or appreciate how responsive this team is", "Steady bombing", "LFG", "WAGMI", "value in nfts is entirely socially based, just like literally everything else in this world", "I can talk about this project all day their roadmap speaks for itself", "Cool arts, nice project, active community, what else would you ask for? We have everything.",
"It'd amaze you to know the number of people I've actually introduced this project to", "I'm forever bullish on this project", "We are gonna make it.", "It's morning here. I haven't eaten breakfast but I'm here already.", "Forever repping this project", 
"Don't listen to anybody trying to sell you whitelist spot.", "To the moon!, We look forward to you boarding our flight!", "Scam!! Beware. They allow fake crypto giveaways to get into your platform and lose all your crypto in seconds if you think it’s them and trust them. Lost 4k 2 weeks ago and they said “sorry”",
"Bro. You guys gotta at least say you're working on android. Cmon now", "i'm so sorry but it's glitchy for me ", "Imagine minting like 10 good projects in a week all in a row", "I also think NFTs are luck", "The community might be good, nice art and it could still flop", "I've witnessed it one time", "I don't really think there's anything like bluechip project until it's successful", 
"All I do everyday is wake up in the morning", "Brush my teeth, tidy up the room and starting dropping messages in discord groups. Wagmi Lmao", "My mum still finds it annoying even though I'm making money off it", "My uncle isn't a crypto type. He dislikes crypto. He believes that they're all ponzi scheme because he got scammed last time he tried.", 
"My uncle bought the squid game token and selling his ethereum because he missed the shiba pump", "He didn't know it was going to be a rug.", "The NFT space is really broad. Like you really need somebody to hold your hand and show you around.", 
"influencers will only take advange of you if you try to navigate by yourself.", "I don't like there's even any crypto course that's credible enough to teach you about NFTs. This space is still new.", "It's a very new space, most of the pariticipants are still early", "And discord isn't really my best  social media app but I don't have a choice lol.", 
"twitter isn't really meant for chatting", "Whatsapp has a limit to how many people that can be a group. ", "And they must not be even more than 500", "My lecturer was talking about NFTs the other day and I kept quiet. ", "Lmao... He sounded so clueless", "I wanted to interrupt but I didn't want my course mates to know I'm into NFTs", "I'm a very private person. That's why I'm not even replying messages that \
much in the discord server.", "Last time I replied someone in discord, they came to my dm and scammed me.", "I'm being being careful out here", "and always minding my business.", "I think I'm more like my mom. She's very private person", "Am I the only one who doesn't consider rarity before selling my NFTs", "someone told me it's best to buy 3 nfts and I thought about it and it makes sense.", 
"3 nfts, one is for you to sell quick immediately after it has been listed, the second one is for you to sell after the pumps. Then the 3rd one will be to see how far the price can go in the future.", "But most time, it is either I don't have enough money to mint 3 or I'm scared to even hodl", 
"You can't imagine the number of people that will fly back to trading bitcoin the moments it starts pumping. ", "We're here because we feel like this is another avenue to make cool money", "It's fun to see people who are whitelisted to even wanna continue chatting in the group. Love  y'all", 
"Somehow feel like I’m oversharing & my kind heart would only put me into troubles.", "I'm watching documentaries and videos on it every months, love it", 
"thats a more conservative way of playing and can get you smaller, but consistent profit", "aright ill be here then", "I only but a seed in this garden of flowers that you prepared my master 😄", 
"Gm team hope everyone is well", "Yeah everything feels so organic here. I love it too. is it okay to post it on twitter and tag you guys", "I bought derivative of bored ape and I lost $2k. My worst mistake ever!", 
"I know this is wrong to say but I find it difficult to risk what I can afford to lose.", "Those games were hard for me bc I’m such a slow typer", "For a project this promising, might be less than expected. In any case, almost all projects have paper hands one way or another. Most just wait it out and ofc keep the community strong", 
"Yes, every project has paperhands. Take normally about a month for them to fold, whereafter price can increase nicely", "school starts next week we're currently on strike","good start to the morning. coffee and nfts. u?", 
"crazy tho the internet is so advanced that we can talk from the other sides of the world", "Hahah…That’s what made love the project in the first place…insane utility, every new devs in town would want it cos it saves them a lot of money magic eden would’ve requested for", 
"Been exposed to crypto since 2018 but i failed many times", "It's hot in here", "Reasonable then", "This project will worth it for sure", "Amazing Project", "Please don’t be a paperhand ok?", "We will be great together", "❤️❤️❤️❤️ we are in this together", "This whitelist is near", "Go go it a amazing project keep hard work then you success🏆", "I guess everyone here is chat botting", 
"it was a joke, didnt mean to offend anyone", "damn thats wild", "No it was a rug the 2.0 was taken over by diff ppl and backed by ME", "need to mint this for new pfp", "OUR PROFITS SKYROCKETED THIS WEEK BABY THANKS TO THAT DUDE", "I made a little bit lately, I need to pay more attention to his calls. Im holding cosmic condos right now", "I love this community keep vibing fam", "Patient is a virtue", 
"Try your level best and give best to community and help newbie", "hope i get wl soon", "Oh thanks for the valuable information 😜", "really need to invest into an incoming bluechip ... hope orochi it's one of them", "Hard work then you can get this wl", "we all gonna make it trust the process fam", "WHAT'S YOUR GREATEST FLIP GUYS?", "The wl spots getting lesser omg", "just be kind and keep the good vibes fam!!", 
"anyone wanna mint like 50 of this?", "yea I saw that they had a ton. So I am just gonna be patient. I am happy I got it done before they made the requirements harder", "yeah. I do only solanas. Can't do eth. Gas fees are so high.", "The Excellent service provider team workers who are ready to take the project to the moon Moon", "The great achiever developer and amazing project", "Yes bro a amazing project keep hard work then you can successful", 
"this project likely a potential nft", "How many nft's can wl member get?", "I ddn't know they were planning to be staking it. I sold mine very early.", "anything worth minting today", "We need to grind if you want somethin work hard to get it bro", "I've literally forgotten lmao", "I don't know but keep hard work then you can sucess", "anyone in botborgs?", "Level up together!", "By posting memes and fan art we can also increase xp guys", "Why ask questions project is good just go", 
"I want to join a DAO can anyone help me with one", "In a nutshell, someone should explain to me what a DAO means.", "No doubt 😊", "i got refused from the uni so i started doing crypto lmao", "still time to get it", "Lets do this dont stop", "Go go go keep try", "Let go the diamond hands", "U guys might wanna visit here ill give u free tour on some landminrs and bomb making facility", "Keep going guys..I hope can get 1 spot here 😁🍻", "We got plenty of different bombs come in any shapes and sizes", 
"Y'all guys know Brando? Pretty smart when it comes to NFTs!", "My friend bought an NFT on polygon for $1900 And sold for 20eth", "We here to make sure this is the next champion", "Go go it's a amazing project dot miss it", "Help each other and keep smiling and grinding", "I THINK THIS PROJECT CAN BE THE NEXT BLUECHIP HONESTLY", "guys wl is soooooooooo tough aaah", "and I'm done with my work ! let's gooooooo finally I'm going to take some reeeeeeest", "Keep greeding this project then you can success", 
"I will not give up", "Please active this project it a amazing project", "Lets grind till our fingers get numb", "This chat gon earn you a fortune", "Go go it a nice project don't miss", "Nigerians, Indians and Phillipines are usually everywhere grinding.", "Everyday man in the block, grinding", "Im an elite solizen can i become a Wl here", "theres still a lot of time for WL left lol", "Kiss my feet guys please iloveyou all love this community", "Kiss my feet guys please iloveyou all love this community lets end racism", 
"If u are paperhand don’t bother to get the WL >.<", "dont you guys love the cool looking NFT of shizen orochi? might hold a couple of it", "dont you guys love the cool looking NFT of shizen orochi? might hold a couple of it", "Might be the 2nd nft that I'm close to getting a wl lately after mono locco", "But we need to do it because the project is fuckin cool", "Always staying active mates! I live talking with you guys :yellow_heart:", "We are going very well, friends, we are standing for a purpose in this sate.", "Means a lot man I see lots of people not even having convos just spamming and stuff. Keeping the community nice and clean I mess with it",
"Most flippers dont think long term!! Literally", "I'll make one art and meme tomorrow", "Hello buddy. Welcome to the gang. If there's any questions please just ask. Anyone here would help you", "Dont stop and no sleep for today guys", "Just grinding since morning. Haven't even eaten breakfast", "My day was brightened by exploring this project and joining the community.", "Yeah technology changing our lives", "Dev free airdrops please", "Make good use of your time guys. If you are planned and programmed, you will not miss anything.", "I think you've gotten over the hard part once you get used to the community. You can win WL anytime, just be a good community member!", 
"I usually check their twitter, how easy it is to get whitelist, their discord members, and their market place", "Disable dms guys lots of bot scams", "this is for sure mooning", "Keep your spirit high guys. We are closer than u think", "Can’t wait to make it my pfp", "im that type of person that will spend 10 sol on a nft but not 10 usd on nitro", "Anyone know how. To use famous fox site", "Yeah already put it to my watchlist, but i already missed a lot. i dont have time to watch it all.. so im just gonna follow other on going seasonal anime..", "guys ima continue the grind tmrw leave sum wl spots for me ima go to bed", "It must be invaluable for you to transform the experience accumulated over a long period of time into such a project. I respected.", 
"I can make a few memes, and with a little chat, I think I can qualify for wl.", "Yeah this server is soo global, a lot of people from all over the globe..", "this art is just fantastic,the devs also", "amazing that so many people are here", "To the mooooooooon", "Now is the best time to have fun in the community. When the hype comes, we can't catch the flow of the chat.", "Just chill and talk in chat pretty much, try to be helpful to new people! I dont think they care about the spammers to much but the people actually having conversations", "Lol dont'mind anybody sending you a dm. It's all scam and scam and scam", "This project is a must win!! Weather you are long term or quick flipper!", "grind keeps going harder and harder", "patience and we will be rewarded", 
"I hate discord scams man I feel so bad for the people that actually click the links in the dm's and get scammed its like taking money out of the nft world", 'That way we can sleep peacfully',  "This is easily one of the biggest projects of 2022. Cant wait to see what this team has to offer.", "lmfao grind dont stop tho", "Yes, there are many, it's annoying, but I still wanted to try my luck.", "Let’s get to it hommie", "I’m just an Island girl, trying to make it", "Yes, I'm paying attention to that. I carefully choose the projects I participate in.", "hard works gonna pay boyz., keep movin", "Im not hating you know but its just the thing ive seen in previous projects", "Has a bit of work to do finished it up and right back to help everyone and vibe", 
"lol just chat and youll make it quicker", "i  could not mint suites and then heard of SHIZEN could not miss this one", "I also like your attitude. Spam-ridden projects are tiring. In most projects, everyone is trying to forcibly take wl.", "You and I can make that happen", "Some friends are trying to level up by writing short messages. They form a part that I dislike not only in this project, but in all projects.", "I know we can make it guys WAGMIII", "I think we need more active and be patient also engage community buddy , ang also trust yourself that you can do it", "Episode was dope bro!!!!!! Thanks for the storyline and amazing artwork.", "NFT project that limits you to minting only one will always turn out to be successful. My opinion though", 
"Matter of time. We're going back to the moon", "Your world will become better for sure", "Grinding with some music on are the best combo, wish yall great! Have a nice day everyone", "Dont feel rushing over, still plenty of time and chances!", "I love the community of this project man. I do not have the opportunity to be bored while chatting among you! I hope everyone who values â€‹â€‹the project manages to get WL.", "I wish I can cop from paperhands at secondary", "Also, since I started NFTs, I don't follow the tradingview screen as often as I used to.", 




]

"""
This words will deliberate on anything that has to do with trading platforms, their techinical issues and how they handle it.(Their support)
"""
trading_platforms = ["hello team, i just want to know if this project has been doxxed", "Balloonville was nearly a rug. Just that magic eden took over the project", "That's why magic eden do requests for IDs before they would support your project", "Nothing's as annoying as when you try minting on magic eden and it's just slow", 
"My 2nd nft got rugged it was a balloonsvillieCrying face I’m currently a bbsolana holderRed heart this would make my day better", "In case magic Eden can’t equal to the task, check LaunchLabs_sol this is what you deserve !", "It happened the same day I was clicking the mint button. It didn't work\
and I had enough Solana. I was just there clicking the button until I saw sold out. So annoying!", "Magic eden should work on being fair to their customers without the need of publicity... Unverifying NFTs that they sold to ppl is very bad... 🤦‍♂️🤦‍♂️ If you sold something you should take responsibility for it", 
"Sometimes  art gets stolen and listed on your magic eden. After they explicitly told about verifying collections ? Are they lying or they simply don't care about collectors and communities ?\
Sigh 😔", "I remember disabling my dm from receiving messages from strangers until I entered this channel that prompted me to enable dm before I could verify. After enabling it, I forgot to turn if off.", "Phishing seems to be heating up. Please know that MODs will never DM you first to ask you for your personal details.\
Especially for newbies in here", "These days, If I'm not whitelisted, I don't even bother minting because it's very obvious I won't get a change of minting.", "How long will it take to list on magic eden?", "Phantom wallet tweeted that some people didn't actually connect to the real Magic eden.", "I was messaged by a spoof Magic Eden account after commenting on one of your posts. Looked legit until the broken English and after they sent a weird link.", 
"I don't know. But I think launchlabs and monkey labs has huge potential", "Has anyone tried transferring their nfts to different wallet address on magid ff", "Who got the phantom wallet pip airdrop?", "Phantom is still better than metamask for me. I love the user interface.", 
"is it me or @phantom wallet got SUPER FAST ???", "initial load up time is still ridiculous on ios. solflare instantly allows u to navigate thru the app upon opening. phantom takes anywhere from 5-10 seconds","Need support!  Is it safe to create a second wallet to send off unknown-unwanted airdrop coins and NFTs that look scammy?", 
"All these FUD scare me  but I’m actually reading carefully the wp and projects road map and it's great.", "Any idea about when phantom wallet may be developing wallet for android app?", "but screenshot is shiit tbh. Any way to download NFT from phantom?", 
"When i open solanart from pc my, wallet name appears as mine bonfida naming service. But not on the mobile phantom. Why and when:)", "I bought the solana domain but didn't get the airdrop", "Getting aidrops these days is similar to getting whitelisted", "And even most airdrops don't even have value", "It will take a while", 
"Most solana NFTs will eventually go to zero. So hodl with caution.", "I didn't receive Magic Eden Airdrop",  "THERE ARE TWO KEYSRF"
]

def words_spiller():
	number = word + trading_platforms + helping_members
	return number

print(len(words_spiller()))